### ISSUE TITLE
Call to ImageArchiver causes nonnumeric port and time out errors

### ISSUE THREAD

**Issue by AyushiG123** [PurdueCAM2Project/CAM2ImageArchiver#15]
The python script which calls the ImageArchiver looks like this:

![screenshot 2019-03-07 at 12 33 42 am](https://user-images.githubusercontent.com/32406375/53934403-b6dd9300-4070-11e9-927d-05a57fac4681.png)

On running the above script, it produces nonnumeric port and time out errors like this:

![screenshot 2019-03-07 at 12 31 32 am](https://user-images.githubusercontent.com/32406375/53934345-81d14080-4070-11e9-89b2-c881d685535d.png)

**Comment by moealani** [comment]
Hey Ayushi,

I fixed the problem in the ImageArchiver and I merged the changes. However, I am still in the process on releasing the fix on PyPi. In the meantime, you can install the new version from source if it's urgent.

**Comment by moealani** [comment]
Issue has been resolved by fixing the problem and generating a distribution to PyPi
